
name: Building the project
on: push
jobs: 
  build-project: 
    name: Build Project
    runs-on: ubuntu-lates
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build
      
      - name: Upload the artifactory image
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-site
          path: .next/

  release-project: 
    name: Release the project
    runs-on: ubuntu-latest
    needs: build-project
    steps: 
      - name: Dowloading the artifact 
        uses: actions/download-artifact@v4
        with: 
          name: nextjs-site
      
      - name: Test Artifact
        run: ls -R 

      
